#!/usr/bin/env node

var sys = require('sys');

var ev = require('./lib/input_event');

var src = ev.createInputEventSource("/dev/input/by-path/platform-i8042-serio-0-event-kbd");
src.on('keyPressed', function(event) {
    sys.puts('key pressed: ' + sys.inspect(event));
})
src.on('keyReleased', function(event) {
    sys.puts('key released: ' + sys.inspect(event));
})
